version: '3'
services:
  node_web:
    container_name: node_web
    build: .
    restart: always
    volumes:
      - build_react:/var/www/html

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - node_web

volumes:
  build_react: